---
version: "3.7"
services:
  proxy:
    build:
      context: ./proxy
    image: example/${APP_NAME}-proxy:${APP_VERSION}
    ports:
      - 80:80
      - 443:443

  processor:
    build:
      context: ./processor
    image: example/${APP_NAME}-processor:${APP_VERSION}
    environment:
      LOGLEVEL: warn
      PORT: 3000

  api:
    build:
      context: ./api
    image: example/${APP_NAME}-api:${APP_VERSION}
    environment:
      LOGLEVEL: warn
      PORT: 3000
      XDEBUG_MODE: "off"
    depends_on:
      - processor

  gui:
    build:
      context: ./gui
    image: example/${APP_NAME}-gui:${APP_VERSION}
    depends_on:
      - api
    environment:
      LOGLEVEL: warn
      PORT: 3000
