---
version: "3.7"
services:
  database:
    image: mongo:3.4.6

  smtp:
    build:
      context: ./smtp
      args:
        MAILHOG_VERSION: ${MAILHOG_VERSION}
        MAILHOG_AUTH_FILE: /var/mailhog_auth
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:${MAILHOG_PORT}
      - MH_UI_BIND_ADDR=0.0.0.0:${MAILHOG_PORT}
      - MH_SMTP_BIND_ADDR=0.0.0.0:${SMTP_PORT}
      - MH_AUTH_FILE=/var/mailhog_auth
      - MH_STORAGE=maildir
    ports:
      - ${MAILHOG_DOCKER_PORT}:${MAILHOG_PORT}
    volumes:
      - ./smtp/htpasswd:/var/mailhog_auth

  # smtp:
  #   image: maildev/maildev:${MAILDEV_VERSION}
  #   environmant:
  #     - MAILDEV_IP=0.0.0.0
  #     - MAILDEV_WEB_IP=0.0.0.0
  #     - MAILDEV_WEB_PORT=${MAILDEV_PORT}
  #     - MAILDEV_SMTP_PORT=${SMTP_PORT}
  #     - MAILDEV_INCOMING_USER=${SMTP_USER}
  #     - MAILDEV_INCOMING_PASS=${SMTP_PASS}
  #     - MAILDEV_WEB_USER=${SMTP_USER}
  #     - MAILDEV_WEB_PASS=${SMTP_PASS}
  #     - MAILDEV_MAIL_DIRECTORY=/tmp/mail
  #   restart: "unless-stopped"
  #   ports:
  #     - ${MAILDEV_PORT}:${MAILDEV_PORT}
  #   volumes:
  #     - ./smtp/mail:/tmp/mail

  processor:
    build:
      target: development
    image: example/${APP_NAME}-processor:${APP_VERSION}-dev
    restart: "unless-stopped"
    environment:
      LOGLEVEL: debug

  authdb:
    image: postgres:11.9-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    networks:
      - auth
    restart: unless-stopped
    volumes:
      - authdb_data:/var/lib/postgresql/data

  auth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - authdb
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: auth
      DATABASE_ROOT_PASSWORD: auth
      DATABASE_USERNAME: auth
      DATABASE_PASSWORD: auth
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://localhost:9011
      SEARCH_TYPE: database
    networks:
     - auth
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - auth_config:/usr/local/fusionauth/config

  api:
    build:
      target: development
    image: example/${APP_NAME}-api:${APP_VERSION}-dev
    restart: "unless-stopped"
    depends_on:
      - database
      - smtp
    environment:
      LOGLEVEL: debug
      XDEBUG_MODE: "${PHP_XDEBUG_MODE:-develop}"
    volumes:
      - ./api/src:/opt/app/src
      - ./api/main.php:/opt/app/main.php

  gui:
    build:
      target: development
    image: example/${APP_NAME}-gui:${APP_VERSION}-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: "unless-stopped"
    volumes:
      - ./gui/src:/opt/app/src
      - ./gui/public:/opt/app/public

networks:
  auth:
    driver: bridge

volumes:
  authdb_data:
  auth_config:
