---
version: "3.7"
services:
  interface:
    build:
      target: development
    image: example/${APP_NAME}-interface:${APP_VERSION}-dev
    restart: "unless-stopped"
    volumes:
      - ./interface/src:/opt/app/src
      - ./interface/public:/opt/app/public

  rest-api:
    build:
      target: development
    image: example/${APP_NAME}-rest-api:${APP_VERSION}-dev
    restart: "unless-stopped"
    depends_on:
      - database
    environment:
      LOGLEVEL: debug
      XDEBUG_MODE: "${PHP_XDEBUG_MODE:-develop}"
    volumes:
      - ./rest-api/src:/opt/app/src
      - ./rest-api/main.php:/opt/app/main.php

  processor:
    build:
      target: development
    image: example/${APP_NAME}-processor:${APP_VERSION}-dev
    restart: "unless-stopped"
    environment:
      LOGLEVEL: debug

  database:
    image: mongo:3.4.6

  smtp:
    build:
      context: ./smtp
      args:
        MAILHOG_VERSION: ${MAILHOG_VERSION}
        MAILHOG_AUTH_FILE: /var/mailhog_auth
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:${MAILHOG_PORT}
      - MH_UI_BIND_ADDR=0.0.0.0:${MAILHOG_PORT}
      - MH_SMTP_BIND_ADDR=0.0.0.0:${SMTP_PORT}
      - MH_AUTH_FILE=/var/mailhog_auth
      - MH_STORAGE=maildir
    ports:
      - ${MAILHOG_DOCKER_PORT}:${MAILHOG_PORT}
    volumes:
      - ./smtp/htpasswd:/var/mailhog_auth
